[project]
name = "dd2525-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "pyinstaller>=6.13.0",
    "requests>=2.32.3",
]
